base_config: configs/tts/fs2.yaml
data_dir: 'data/ccom'
stats_data_dir: 'data/stats'
raw_data_dir: 'YOUR_DATA_PATH' # dir includes *.wav and *.lab

# model
dropout: 0.2
max_tokens: 28000
val_check_interval: 1000
max_updates: 200000

lambda_uv: 0.01
lambda_pitch: 0.01
use_uv: true
use_pitch_embed: false
use_energy_embed: false
